name: GitHub部署一个vue项目
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉代码
    - name: Checkout
      uses: actions/checkout@master
    - name: Install and Build
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
        npm install
        npm run build
    - name: Deploy On GitHub Page
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN }}
        BRANCH: release
        FOLDER: dist
        # CLEAN: true
